stages: 
  load_data:
    cmd: python src\load_data.py --config=params.yaml 
    deps:
      - src\get_data.py
      - src\load_data.py
      - data_given\employee.csv
    outs: 
      - data\raw\employee.csv
  

  split_data:
    cmd: python src\split_data.py --config=params.yaml
    deps:
    - src\split_data.py
    - data\raw\employee.csv
    outs:
    - data\processed\train_employee.csv
    - data\processed\test_employee.csv 
