stages: 
  load_data:
    cmd: python src\load_data.py --config=params.yaml 
    deps:
      - src\get_data.py
      - src\load_data.py
      - data_given\employee.csv
    outs: 
      - data\raw\employee.csv
  

  split_data:
    cmd: python src\split_data.py --config=params.yaml
    deps:
    - src\split_data.py
    - data\raw\employee.csv
    outs:
    - data\processed\train_employee.csv
    - data\processed\test_employee.csv 
  
  train_and_evaluate:
    cmd: python src\train_and_evaluate.py --config=params.yaml
    deps:
    - data\processed\train_employee.csv
    - data\processed\test_employee.csv 
    - src\train_and_evaluate.py
    params:
    - estimators.RandomForestClassifier.params.n_estimators
    - estimators.RandomForestClassifier.params.max_feature
    #metrics:
    #- report\scores.json:
    #    cache: false
    #- report\param.json:
    #    cache: false
    #outs:
    #  - saved_models/finalized_model.sav
    
  #log_production_model:
  #  cmd: python src\log_production_model.py --config=params.yaml  
  #  deps: 
  #   - src\log_production_model.py