base:
  project: Employee-Attrition 
  random_state: 42
  target_col: Attrition

data_source:
  s3_source: data_given\employee.csv

load_data:
  raw_dataset_csv: data\raw\employee.csv

split_data:
  train_path: data\processed\train_employee.csv
  test_path: data\processed\test_employee.csv
  test_size: 0.3

estimators:
  RandomForestClassifier:
    params:
      #n_estimators: 100
      #max_feature: 6
      n_estimators: 100
      max_feature: 7
model_dir:
  saved_models 

reports: 
  params: report\param.json
  scores: report\scores.json

webapp_model_dir: prediction_service\\model\\finalized_model.sav 

mlflow_config: 
  artifacts_dir: artifacts 
  experiment_name: RandomForest Classifier
  run_name: mlops
  registered_model_name: RandomForestEmployeeModel
  remote_server_uri: http://127.0.0.1:1234 
  