base:
  project: Employee-Attrition 
  random_state: 42
  target_col: Attrition

data_source:
  s3_source: data_given\employee.csv

load_data:
  raw_dataset_csv: data\raw\employee.csv

split_data:
  train_path: data\processed\train_employee.csv
  test_path: data\processed\test_employee.csv
  test_size: 0.3

estimators:
  RandomForestClassifier:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      n_estimators: 100
      max_feature: 6
model_dir:
  saved_models 

reports: 
  params: report\param.json
  scores: report\scores.json